### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by samelamin** [adaburrows/ethereum-testnet-docker#1]
Cant get the docker images to run. There seems to be an issue with the geth config ?

```
WARN [10-26|15:57:00.856] Config field is deprecated and won't have an effect name=ethconfig.Config.TrieCleanCacheRejournal
Fatal: /root/config.toml, line 8: field 'UltraLightFraction' is not defined in ethconfig.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/ethconfig#Config for available fields
Fatal: /root/config.toml, line 8: field 'UltraLightFraction' is not defined in ethconfig.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/ethconfig#Config for available **fields**
```

**Comment by adaburrows** [comment]
I haven't had time to maintain this, so no. I should probably just archive it. If you're wanting to use something for development and testing of contracts, you should probably just use Hardhat and [it's built-in test network](https://hardhat.org/tutorial/debugging-with-hardhat-network). If you wanted to use it as part of the Interledger dev env I built, then I should probably archive that, too. If you wanted to use for your own network, I put warning up not to use this in production as it's very poorly secured and it's just for testing/educational purposes.
